const CHAT_URL="https://dfvztoazthliaobqnndv.supabase.co/functions/v1/astra-chat-v2";
const STORAGE_KEY="astra-aura-profile-v1";
const $=s=>document.querySelector(s),messages=$("#messages");
const getProfile=()=>JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}
$("#startButton").addEventListener("click",()=>scrollToId("chatPanel"));
$("#profileButton").addEventListener("click",()=>scrollToId("birthPanel"));
document.querySelectorAll(".feature-card").forEach(card=>card.addEventListener("click",()=>{if(card.dataset.mode==="birth")scrollToId("birthPanel");else{scrollToId("chatPanel");$("#messageInput").focus()}}));
document.querySelectorAll(".nav-item").forEach(item=>item.addEventListener("click",()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));item.classList.add("active");if(item.dataset.scroll!=="top")scrollToId(item.dataset.scroll);else window.scrollTo({top:0,behavior:"smooth"})}));
function addMessage(text,type="assistant"){const row=document.createElement("div");row.className="message "+type;row.innerHTML='<div class="message-avatar">'+(type==="user"?"◉":"✦")+'</div><div class="bubble"></div>';row.querySelector(".bubble").textContent=text;messages.appendChild(row);messages.scrollTop=messages.scrollHeight}
async function askAI(value){const profile=getProfile();const externalId=localStorage.getItem("astra-aura-device-id")||crypto.randomUUID();localStorage.setItem("astra-aura-device-id",externalId);const res=await fetch(CHAT_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({channel:"web",external_id:externalId,message:value,profile})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"Ошибка AI");return data.answer}
$("#chatForm").addEventListener("submit",async e=>{e.preventDefault();const input=$("#messageInput"),value=input.value.trim();if(!value)return;addMessage(value,"user");input.value="";const button=$("#chatForm button");button.disabled=true;addMessage("Секунду…");const pending=messages.lastElementChild;try{const answer=await askAI(value);pending.remove();addMessage(answer)}catch(err){pending.remove();addMessage("Не удалось получить ответ. Проверь настройки AI-сервера.")}finally{button.disabled=false}});
const saved=getProfile();if(saved){$("#birthDate").value=saved.date||"";$("#birthTime").value=saved.time||"";$("#birthPlace").value=saved.place||""}
$("#birthForm").addEventListener("submit",e=>{e.preventDefault();const profile={...getProfile(),date:$("#birthDate").value,time:$("#birthTime").value,place:$("#birthPlace").value.trim()};localStorage.setItem(STORAGE_KEY,JSON.stringify(profile));addMessage("Данные рождения сохранены. Теперь я могу использовать их как контекст для символической интерпретации.");scrollToId("chatPanel")});
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));