const SUPABASE_URL=Deno.env.get("SUPABASE_URL")??"";
const SUPABASE_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const INGEST_KEY=Deno.env.get("ASTRA_INGEST_KEY")??"";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-ingest-key","Access-Control-Allow-Methods":"POST, OPTIONS"};
async function db(path:string,options:RequestInit={}){const r=await fetch(SUPABASE_URL+"/rest/v1/"+path,{...options,headers:{apikey:SUPABASE_SERVICE_ROLE_KEY,Authorization:"Bearer "+SUPABASE_SERVICE_ROLE_KEY,"content-type":"application/json",...(options.headers||{})}});if(!r.ok)throw new Error("DB "+r.status+": "+await r.text());const raw=await r.text();return raw.trim()?JSON.parse(raw):null;}
async function requestJson(url:string,init:RequestInit={},timeoutMs=12000){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeoutMs);try{const r=await fetch(url,{...init,signal:ctl.signal});const raw=await r.text();let data:any;try{data=raw.trim()?JSON.parse(raw):null}catch{data={raw:raw.slice(0,5000)}}return{ok:r.ok,status:r.status,data};}catch(e){return{ok:false,status:0,data:{error:String(e)}}}finally{clearTimeout(timer)}}
function dateParts(s:string){const m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)throw new Error("date_must_be_YYYY-MM-DD");return{year:Number(m[1]),month:Number(m[2]),day:Number(m[3])};}
async function save(source:string,key:string,input:any,result:any){await db("numerology_external_cache",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({source_key:source,calculation_key:key,input_data:input,result_data:result,fetched_at:new Date().toISOString(),expires_at:new Date(Date.now()+86400000).toISOString()})});}
async function sourceEnabled(source:string){const r=await db("numerology_external_sources?source_key=eq."+encodeURIComponent(source)+"&select=enabled");return Boolean(r?.[0]?.enabled);}
async function ingest(body:any){
 const date=String(body?.birth_date??"").trim(),name=String(body?.full_name??"").trim(),gender=String(body?.gender??"").trim();const{year,month,day}=dateParts(date),key=date+"|"+name+"|"+gender,input={birth_date:date,full_name:name||null,gender:gender||null},results:any={};
 if(await sourceEnabled("ankshakti")){const r=await requestJson("https://ankshakti.flyingstar.in/api/v1/birth?date="+encodeURIComponent(date));results.ankshakti={status:r.status,ok:r.ok,data:r.data};if(r.ok)await save("ankshakti",key,input,r.data);}
 const nav=Deno.env.get("NAVAMSHA_API_KEY")??"";if(nav&&await sourceEnabled("navamsha")){const r=await requestJson("https://api.navamsha.in/api/v1/numerology/core/life-path",{method:"POST",headers:{"X-API-Key":nav,"Content-Type":"application/json"},body:JSON.stringify({birth_date:date})});results.navamsha={status:r.status,ok:r.ok,data:r.data};if(r.ok)await save("navamsha",key,input,r.data);}else results.navamsha={skipped:true,reason:"NAVAMSHA_API_KEY_not_configured"};
 const dak=Deno.env.get("DAKIDARTS_API_KEY")??"";if(dak&&await sourceEnabled("dakidarts")){const u="https://api.numerologyapi.com/api/v1/life_path?birth_year="+year+"&birth_month="+month+"&birth_day="+day+"&lang=ru&num_sys=pythagorean";const r=await requestJson(u,{headers:{"X-API-Key":dak}});results.dakidarts={status:r.status,ok:r.ok,data:r.data};if(r.ok)await save("dakidarts",key,input,r.data);}else results.dakidarts={skipped:true,reason:"DAKIDARTS_API_KEY_not_configured"};
 const roxy=Deno.env.get("ROXYAPI_KEY")??"";if(roxy&&await sourceEnabled("roxyapi")){const r=await requestJson("https://roxyapi.com/api/v2/numerology/life-path",{method:"POST",headers:{"X-API-Key":roxy,"Content-Type":"application/json"},body:JSON.stringify({year,month,day})});results.roxyapi={status:r.status,ok:r.ok,data:r.data};if(r.ok)await save("roxyapi",key,input,r.data);}else results.roxyapi={skipped:true,reason:"ROXYAPI_KEY_not_configured"};
 const dev=Deno.env.get("DEVDARSHA_API_KEY")??"";if(dev&&await sourceEnabled("devdarsha")){const r=await requestJson("https://panchang.devdarsha.com/v1/numerology/date-numbers",{method:"POST",headers:{"X-Api-Key":dev,"Content-Type":"application/json"},body:JSON.stringify({date_of_birth:date})});results.devdarsha={status:r.status,ok:r.ok,data:r.data};if(r.ok)await save("devdarsha",key,input,r.data);}else results.devdarsha={skipped:true,reason:"DEVDARSHA_API_KEY_not_configured"};
 const divine=Deno.env.get("DIVINEAPI_KEY")??"";if(divine&&name&&gender&&await sourceEnabled("divineapi")){const r=await requestJson("https://astroapi-4.divineapi.com/numerology/v1/core-numbers",{method:"POST",headers:{Authorization:"Bearer "+divine,"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({api_key:divine,full_name:name,day:String(day),month:String(month),year:String(year),gender,method:"pythagorean",lan:"en"}).toString()});results.divineapi={status:r.status,ok:r.ok,data:r.data};if(r.ok)await save("divineapi",key,input,r.data);}else results.divineapi={skipped:true,reason:divine?(name&&gender?"":"full_name_and_gender_required"):"DIVINEAPI_KEY_not_configured"};
 return{ok:true,birth_date:date,full_name:name||null,results};
}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{status:204,headers:cors});try{if(req.method!=="POST")return new Response(JSON.stringify({ok:false,error:"POST_required"}),{status:405,headers:{...cors,"Content-Type":"application/json"}});if(INGEST_KEY){const supplied=req.headers.get("x-ingest-key")??"";if(supplied!==INGEST_KEY)return new Response(JSON.stringify({ok:false,error:"unauthorized"}),{status:401,headers:{...cors,"Content-Type":"application/json"}});}if(!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY)throw new Error("supabase_configuration_missing");return new Response(JSON.stringify(await ingest(await req.json())),{status:200,headers:{...cors,"Content-Type":"application/json"}});}catch(e){console.error(e);return new Response(JSON.stringify({ok:false,error:String(e?.message??e)}),{status:400,headers:{...cors,"Content-Type":"application/json"}})}});
